### PR TITLE
Send the entire script body with the batch request

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
Also load the script once when determining the magic arguments

### CODE REVIEW

**Comment by benarmston** [comment]
This looks good to me.

**Comment by benarmston** [comment]
The `queue` action is broken.

**Comment by WilliamMcCumstie** [comment]
Rebased to resolve merge conflict

Forgot that the `script_name` is used in the queue. The `script_name` is now sent to the server during `batch` so it can be reflected back during `queue`

**Comment by benarmston** [comment]
LGTM.

**Pull request merged**
